{
 "title": "Work Agent",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Requests to Hub Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (rate(rest_client_requests_total{namespace=\"open-cluster-management-agent\", service=\"klusterlet-agent\", host=~\"(api.*)|(kubernetes.default.svc:443)\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration - P75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, max by(verb, le) (rest_client_request_duration_seconds_bucket{namespace=\"open-cluster-management-agent\", service=\"klusterlet-agent\", host=~\"(api.*)|(kubernetes.default.svc:443)\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests to Managed Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(method) (rate(rest_client_requests_total{namespace=\"open-cluster-management-agent\", service=\"klusterlet-agent\", host=\"172.30.0.1:443\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration - P75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, max by(verb, le) (rest_client_request_duration_seconds_bucket{namespace=\"open-cluster-management-agent\", service=\"klusterlet-agent\",host=\"172.30.0.1:443\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Enqueue Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(name) (rate(workqueue_adds_total{namespace=\"open-cluster-management-agent\", name=\"ManifestWorkAgent\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max by(name) (workqueue_depth{namespace=\"open-cluster-management-agent\", name=\"ManifestWorkAgent\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}