{
 "title": "Import Controller",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Managed Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of managed clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "acm_managed_cluster_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Derivative of managed cluster number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "deriv(acm_managed_cluster_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate to hub cluster",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum by(method) (rate(rest_client_requests_total{namespace=\"multicluster-engine\", service=\"import-controller\", host=~\"172.*\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Enqueue rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(controller) (rate(workqueue_adds_total{namespace=\"multicluster-engine\", service=\"import-controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(controller) (workqueue_depth{namespace=\"multicluster-engine\", service=\"import-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P75 - Reconciliation duration (second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, max by(controller, le) (controller_runtime_reconcile_time_seconds_bucket{namespace=\"multicluster-engine\", service=\"import-controller\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(controller) (rate (controller_runtime_reconcile_total{namespace=\"multicluster-engine\", service=\"import-controller\", result=\"error\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}